import {createHash} from "node:crypto";
import {execFileSync} from "node:child_process";
import {
  copyFileSync,
  cpSync,
  mkdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import {basename, join, relative, resolve} from "node:path";
import {fileURLToPath} from "node:url";

const workspaceRoot = fileURLToPath(new URL("../", import.meta.url));
const repoRoot = fileURLToPath(new URL("../../../", import.meta.url));
const outputRoot = join(repoRoot, "output", "promo-video");
const entryPoint = join(workspaceRoot, "src", "index.tsx");
const remotion = join(workspaceRoot, "node_modules", "@remotion", "cli", "remotion-cli.js");
const remotionBinaries = prepareRemotionBinaries();
const ffmpeg = findOnPath(process.platform === "win32" ? "ffmpeg.exe" : "ffmpeg");
const ffprobe = findOnPath(process.platform === "win32" ? "ffprobe.exe" : "ffprobe");
const soundtrack = join(workspaceRoot, "public", "generated", "audio", "bookmarkflow-bed.wav");

assertSafeOutput(outputRoot);
rmSync(outputRoot, {recursive: true, force: true});
mkdirSync(outputRoot, {recursive: true});

execFileSync(process.execPath, [join(workspaceRoot, "scripts", "prepare-assets.mjs")], {
  cwd: workspaceRoot,
  stdio: "inherit",
});

const renders = [
  ["BookmarkFlowMaster", "bookmarkflow-bar-master-1920x1080.mp4", 58],
  ["BookmarkFlowX", "bookmarkflow-bar-x-1920x1080.mp4", 32],
  ["BookmarkFlowTeaser", "bookmarkflow-bar-teaser-1080x1350.mp4", 15],
];

for (const [composition, outputName, duration] of renders) {
  const finalOutput = join(outputRoot, outputName);
  const videoOnlyOutput = join(outputRoot, `.${outputName}.video-only.mp4`);
  runRemotion([
    "render",
    entryPoint,
    composition,
    videoOnlyOutput,
    "--codec=h264",
    "--crf=18",
    "--pixel-format=yuv420p",
    "--muted",
    "--concurrency=4",
    "--overwrite",
  ]);
  muxSoundtrack({videoOnlyOutput, finalOutput, duration});
  rmSync(videoOnlyOutput, {force: true});
}

runRemotion([
  "still",
  entryPoint,
  "BookmarkFlowPoster",
  join(outputRoot, "bookmarkflow-bar-poster-1920x1080.png"),
  "--image-format=png",
  "--overwrite",
]);

copyFileSync(
  join(outputRoot, "bookmarkflow-bar-master-1920x1080.mp4"),
  join(outputRoot, "bookmarkflow-bar-linkedin-1920x1080.mp4"),
);
copyFileSync(
  join(workspaceRoot, "captions", "bookmarkflow-master.en.srt"),
  join(outputRoot, "bookmarkflow-bar-master.en.srt"),
);
copyFileSync(
  join(workspaceRoot, "captions", "bookmarkflow-x.en.srt"),
  join(outputRoot, "bookmarkflow-bar-x.en.srt"),
);

execFileSync(
  ffmpeg,
  [
    "-hide_banner",
    "-loglevel",
    "error",
    "-y",
    "-ss",
    "4.4",
    "-t",
    "4.6",
    "-i",
    join(outputRoot, "bookmarkflow-bar-master-1920x1080.mp4"),
    "-filter_complex",
    "[0:v]fps=12,scale=960:540:flags=lanczos,split[a][b];[a]palettegen=max_colors=96:reserve_transparent=0[p];[b][p]paletteuse=dither=sierra2_4a",
    "-loop",
    "-1",
    join(outputRoot, "bookmarkflow-bar-preview-960x540.gif"),
  ],
  {cwd: repoRoot, stdio: "inherit"},
);

const outputFiles = [
  ...renders.map(([, name]) => name),
  "bookmarkflow-bar-linkedin-1920x1080.mp4",
  "bookmarkflow-bar-poster-1920x1080.png",
  "bookmarkflow-bar-preview-960x540.gif",
  "bookmarkflow-bar-master.en.srt",
  "bookmarkflow-bar-x.en.srt",
];
const artifacts = outputFiles.map((name) => describeOutput(join(outputRoot, name)));
assertArtifactContracts(artifacts);
const manifest = {
  schemaVersion: 1,
  status: "PREPARED_NOT_UPLOADED",
  generatedAt: new Date().toISOString(),
  sourceRevision: git(["rev-parse", "HEAD"]).trim(),
  safety: {
    data: "Only synthetic, provenance-reviewed bookmark media is visible.",
    network: "No remote runtime media is used by the compositions.",
    rights: "Typography is system-rendered; the deterministic bright electronic bed is generated by project code.",
  },
  artifacts,
};

writeFileSync(join(outputRoot, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
writeFileSync(
  join(outputRoot, "SHA256SUMS.txt"),
  `${artifacts.map(({sha256, path}) => `${sha256}  ${path}`).join("\n")}\n`,
  "utf8",
);

console.log(`Rendered and verified ${artifacts.length} promo artifacts in ${outputRoot}`);

function runRemotion(args) {
  const binaryArgs = remotionBinaries
    ? [`--binaries-directory=${remotionBinaries}`]
    : [];
  execFileSync(
    process.execPath,
    [remotion, ...args, ...binaryArgs],
    {cwd: workspaceRoot, stdio: "inherit"},
  );
}

function muxSoundtrack({videoOnlyOutput, finalOutput, duration}) {
  execFileSync(
    ffmpeg,
    [
      "-hide_banner",
      "-loglevel",
      "error",
      "-y",
      "-i",
      videoOnlyOutput,
      "-i",
      soundtrack,
      "-t",
      String(duration),
      "-map",
      "0:v:0",
      "-map",
      "1:a:0",
      "-c:v",
      "libx264",
      "-preset",
      "medium",
      "-crf",
      "18",
      "-vf",
      "scale=in_range=full:out_range=tv",
      "-pix_fmt",
      "yuv420p",
      "-color_range",
      "tv",
      "-colorspace",
      "bt709",
      "-color_primaries",
      "bt709",
      "-color_trc",
      "bt709",
      "-c:a",
      "aac",
      "-b:a",
      "192k",
      "-shortest",
      "-movflags",
      "+faststart",
      finalOutput,
    ],
    {cwd: repoRoot, stdio: "inherit"},
  );
}

function prepareRemotionBinaries() {
  if (process.platform !== "win32") return null;
  const source = join(
    workspaceRoot,
    "node_modules",
    "@remotion",
    "compositor-win32-x64-msvc",
  );
  const target = join(workspaceRoot, ".remotion", "system-binaries");
  if (!resolve(target).toLowerCase().startsWith(resolve(workspaceRoot).toLowerCase())) {
    throw new Error(`Refusing to prepare Remotion binaries outside the workspace: ${target}`);
  }
  rmSync(target, {recursive: true, force: true});
  mkdirSync(target, {recursive: true});
  cpSync(source, target, {recursive: true});
  copyFileSync(findOnPath("ffmpeg.exe"), join(target, "ffmpeg.exe"));
  copyFileSync(findOnPath("ffprobe.exe"), join(target, "ffprobe.exe"));
  return target;
}

function findOnPath(executable) {
  const locator = process.platform === "win32" ? "where.exe" : "which";
  const paths = execFileSync(locator, [executable], {encoding: "utf8"})
    .split(/\r?\n/u)
    .map((entry) => entry.trim())
    .filter(Boolean);
  if (!paths[0]) throw new Error(`${executable} is required for deterministic promo rendering`);
  return paths[0];
}

function describeOutput(path) {
  const extension = basename(path).split(".").at(-1).toLowerCase();
  const description = {
    path: relative(outputRoot, path).replaceAll("\\", "/"),
    bytes: statSync(path).size,
    sha256: sha256(path),
  };
  if (["mp4", "png", "gif"].includes(extension)) {
    const probe = JSON.parse(execFileSync(
      ffprobe,
      ["-v", "error", "-show_streams", "-show_format", "-of", "json", path],
      {encoding: "utf8"},
    ));
    return {...description, probe};
  }
  return description;
}

function sha256(path) {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

function assertArtifactContracts(artifacts) {
  const expectedVideos = new Map([
    ["bookmarkflow-bar-master-1920x1080.mp4", [1920, 1080, 58]],
    ["bookmarkflow-bar-linkedin-1920x1080.mp4", [1920, 1080, 58]],
    ["bookmarkflow-bar-x-1920x1080.mp4", [1920, 1080, 32]],
    ["bookmarkflow-bar-teaser-1080x1350.mp4", [1080, 1350, 15]],
  ]);
  for (const [name, [width, height, duration]] of expectedVideos) {
    const artifact = artifacts.find(({path}) => path === name);
    const video = artifact?.probe?.streams?.find(({codec_type: type}) => type === "video");
    const audio = artifact?.probe?.streams?.find(({codec_type: type}) => type === "audio");
    const actualDuration = Number(artifact?.probe?.format?.duration);
    if (
      video?.codec_name !== "h264"
      || video?.pix_fmt !== "yuv420p"
      || video?.width !== width
      || video?.height !== height
      || audio?.codec_name !== "aac"
      || Math.abs(actualDuration - duration) > 0.12
    ) {
      throw new Error(`${name}: rendered video does not match its H.264/AAC/dimension/duration contract`);
    }
  }

  const poster = artifacts.find(({path}) => path === "bookmarkflow-bar-poster-1920x1080.png");
  const posterVideo = poster?.probe?.streams?.find(({codec_type: type}) => type === "video");
  if (posterVideo?.codec_name !== "png" || posterVideo?.width !== 1920 || posterVideo?.height !== 1080) {
    throw new Error("Poster does not match its reviewed 1920x1080 PNG contract");
  }

  const preview = artifacts.find(({path}) => path === "bookmarkflow-bar-preview-960x540.gif");
  const previewVideo = preview?.probe?.streams?.find(({codec_type: type}) => type === "video");
  const previewDuration = Number(preview?.probe?.format?.duration);
  const previewBytes = readFileSync(join(outputRoot, "bookmarkflow-bar-preview-960x540.gif"));
  if (
    previewVideo?.codec_name !== "gif"
    || previewVideo?.width !== 960
    || previewVideo?.height !== 540
    || previewDuration <= 0
    || previewDuration > 5
    || previewBytes.toString("latin1").includes("NETSCAPE2.0")
  ) {
    throw new Error("Preview GIF must be 960x540, animated for at most five seconds, and play once");
  }
}

function git(args) {
  return execFileSync("git", args, {cwd: repoRoot, encoding: "utf8"});
}

function assertSafeOutput(path) {
  const expected = resolve(repoRoot, "output", "promo-video").toLowerCase();
  if (resolve(path).toLowerCase() !== expected) {
    throw new Error(`Refusing to clear an unexpected output path: ${path}`);
  }
}
